2025-08-04 16:58:51,185 - modelscope - INFO - Server name updated from "stdio-python" to "test-server"
2025-08-04 16:58:51,185 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,185 - modelscope - ERROR - MCP error calling tool tool1 on server test-server: Connection lost
2025-08-04 16:58:51,190 - modelscope - INFO - Server name updated from "streamable_http-api" to "test-server"
2025-08-04 16:58:51,190 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,193 - modelscope - INFO - Server name updated from "sse-api" to "test-server"
2025-08-04 16:58:51,193 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,194 - modelscope - ERROR - Failed to connect to server sse-api: Connection refused
2025-08-04 16:58:51,196 - modelscope - INFO - Server name updated from "stdio-python" to "test-server"
2025-08-04 16:58:51,196 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,199 - modelscope - INFO - Server name updated from "sse-api" to "test-server"
2025-08-04 16:58:51,199 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,202 - modelscope - INFO - Server name updated from "stdio-python" to "test-server"
2025-08-04 16:58:51,202 - modelscope - INFO - Connected to server test-server
2025-08-04 16:58:51,205 - modelscope - INFO - Server name updated from "streamable_http-api" to "test-server"
2025-08-04 16:58:51,205 - modelscope - INFO - Connected to server test-server
